### ISSUE TITLE
Shared Lib compilation Issue 

### ISSUE THREAD

**Issue by Muhayyuddin** [webrtc-sdk/libwebrtc#1]
Hi
 I have tried to generate dynamic lib by performing the following steps.

-    source the depot-tools
-     cloned webrtc branch-head/m74
-     clone you project in webrtc/src
-     modified the main BUILD.gn file  in webrtc/src folder by adding the line as you have mentioned in readme  
        group("default") {
           testonly = true
           deps = [
          ":webrtc",
         "//libwebrtc:libwebrtc",
          ]
    
-  gn gen out/default "--args=enable_iterator_debugging=false is_component_build=false is_debug=false"   
- ninja -C out/Default libwebrtc

    it generates the following error 
``` shell
webrtc@webrtc-Virtual-Machine:~/webRTC/webrtc-checkout/src$  ninja -C out/Default libwebrtc
ninja: Entering directory `out/Default'
[1/1] Regenerating ninja files
FAILED: build.ninja
../../buildtools/linux64/gn --root=../.. -q gen .
ERROR at //BUILD.gn:33:31: Invalid token.
      "//libwebrtc:libwebrtc",
                              ^
You got a tab character in here. Tabs are evil. Convert to spaces.
ninja: error: rebuilding 'build.ninja': subcommand failed
```
What do you think What could be the potential issue?

Regards
GM

**Comment by Muhayyuddin** [comment]
Hi 
I have fixed the above issue, when I run BUILD.gn file that in libwebrtc [webrtc-checkout/src/libwebrtc/] then it started compiling. 

Now I have another issue after compiling around 90% It generates the error as below 

``` shell
ninja: build stopped: subcommand failed.
webrtc@webrtc-Virtual-Machine:~/webRTC/webrtc-checkout/src/libwebrtc$ ninja -C out/Default libwebrtc
ninja: Entering directory `out/Default'
[3/95] CXX obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o
FAILED: obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o 
../../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o.d -DUSE_LIBYUV -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"354873-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=354212 -DCR_LIBCXXABI_REVISION=354284 -D_LIBCPP_ENABLE_NODISCARD -DCR_SYSROOT_HASH=e7c53f04bd88d29d075bfd1f62b073aeb69cbe09 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWEBRTC_ENABLE_PROTOBUF=1 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DRTC_ENABLE_VP9 -DHAVE_SCTP -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DHAVE_WEBRTC_VIDEO -I../../../libwebrtc -I../../../libwebrtc/include -I../../.. -Igen -I../../../third_party/abseil-cpp -I../../../libwebrtc/include -I../../../third_party/libyuv/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf -ggnu-pubnames -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wc++11-narrowing -Wimplicit-fallthrough -Wthread-safety -Winconsistent-missing-override -Wundef -Wunused-lambda-capture -Wno-shorten-64-to-32 -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++11 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../../buildtools/third_party/libc++/trunk/include -isystem../../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../../libwebrtc/src/rtc_peerconnection_factory_impl.cc -o obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o
../../../libwebrtc/src/rtc_peerconnection_factory_impl.cc:75:112: error: too many arguments to function call, expected single argument 'audio_layer', have 2 arguments
    audio_device_module_ = webrtc::AudioDeviceModule::Create(webrtc::AudioDeviceModule::kPlatformDefaultAudio, nullptr);
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                   ^~~~~~~
../../../modules/audio_device/include/audio_device.h:45:3: note: 'Create' declared here
  static rtc::scoped_refptr<AudioDeviceModule> Create(
  ^
1 error generated.

```
I have clones WebRTC branch-head/m74 is it the correct version by seeing the above error it seems that the argument of the function are modified. when I change the argument of the function then it generates some other error. 
how can we fix it, branch-head/m74 is compatible with it ?

**Comment by Muhayyuddin** [comment]
Hi,
Finally I have fixed the issue by removing the second argument of the create function in rtc_peerconnection... at multiple places. It generated the .so file 
Thank you :-)

Regards
GM

**Comment by cloudwebrtc** [comment]
@Muhayyuddin 
Sorry for this late reply, the project currently only confirms that the M72 can work fine. The libwebrtc for M74 can only be compiled and passed without testing.

**Comment by Muhayyuddin** [comment]
@cloudwebrtc I have compiled with M74 the .so is generated successfully. I would like to know how can I link this dynamic library to compile peerconnection client example or any sample code for media streaming will be great.

**Comment by cloudwebrtc** [comment]
I refer to the JS API to wrap libwebrtc, you can try to read the js API to write the program, and I will write test cases in the future.

**Comment by liyi6** [comment]
> Hi
> I have fixed the above issue, when I run BUILD.gn file that in libwebrtc [webrtc-checkout/src/libwebrtc/] then it started compiling.
> 
> Now I have another issue after compiling around 90% It generates the error as below
> 
> ```shell
> ninja: build stopped: subcommand failed.
> webrtc@webrtc-Virtual-Machine:~/webRTC/webrtc-checkout/src/libwebrtc$ ninja -C out/Default libwebrtc
> ninja: Entering directory `out/Default'
> [3/95] CXX obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o
> FAILED: obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o 
> ../../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o.d -DUSE_LIBYUV -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"354873-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=354212 -DCR_LIBCXXABI_REVISION=354284 -D_LIBCPP_ENABLE_NODISCARD -DCR_SYSROOT_HASH=e7c53f04bd88d29d075bfd1f62b073aeb69cbe09 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWEBRTC_ENABLE_PROTOBUF=1 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DRTC_ENABLE_VP9 -DHAVE_SCTP -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DHAVE_WEBRTC_VIDEO -I../../../libwebrtc -I../../../libwebrtc/include -I../../.. -Igen -I../../../third_party/abseil-cpp -I../../../libwebrtc/include -I../../../third_party/libyuv/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf -ggnu-pubnames -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wc++11-narrowing -Wimplicit-fallthrough -Wthread-safety -Winconsistent-missing-override -Wundef -Wunused-lambda-capture -Wno-shorten-64-to-32 -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++11 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../../buildtools/third_party/libc++/trunk/include -isystem../../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../../libwebrtc/src/rtc_peerconnection_factory_impl.cc -o obj/libwebrtc/libwebrtc/rtc_peerconnection_factory_impl.o
> ../../../libwebrtc/src/rtc_peerconnection_factory_impl.cc:75:112: error: too many arguments to function call, expected single argument 'audio_layer', have 2 arguments
>     audio_device_module_ = webrtc::AudioDeviceModule::Create(webrtc::AudioDeviceModule::kPlatformDefaultAudio, nullptr);
>                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                   ^~~~~~~
> ../../../modules/audio_device/include/audio_device.h:45:3: note: 'Create' declared here
>   static rtc::scoped_refptr<AudioDeviceModule> Create(
>   ^
> 1 error generated.
> ```
> 
> I have clones WebRTC branch-head/m74 is it the correct version by seeing the above error it seems that the argument of the function are modified. when I change the argument of the function then it generates some other error.
> how can we fix it, branch-head/m74 is compatible with it ?



> Hi
> I have tried to generate dynamic lib by performing the following steps.
> 
> * source the depot-tools
> * ```
>   cloned webrtc branch-head/m74
>   ```
> * ```
>   clone you project in webrtc/src
>   ```
> * ```
>   modified the main BUILD.gn file  in webrtc/src folder by adding the line as you have mentioned in readme  
>     group("default") {
>        testonly = true
>        deps = [
>       ":webrtc",
>      "//libwebrtc:libwebrtc",
>       ]
>   ```
> * gn gen out/default "--args=enable_iterator_debugging=false is_component_build=false is_debug=false"
> * ninja -C out/Default libwebrtc
>   it generates the following error
> 
> ```shell
> webrtc@webrtc-Virtual-Machine:~/webRTC/webrtc-checkout/src$  ninja -C out/Default libwebrtc
> ninja: Entering directory `out/Default'
> [1/1] Regenerating ninja files
> FAILED: build.ninja
> ../../buildtools/linux64/gn --root=../.. -q gen .
> ERROR at //BUILD.gn:33:31: Invalid token.
>       "//libwebrtc:libwebrtc",
>                               ^
> You got a tab character in here. Tabs are evil. Convert to spaces.
> ninja: error: rebuilding 'build.ninja': subcommand failed
> ```
> 
> What do you think What could be the potential issue?
> 
> Regards
> GM

hello, can you tell us how you fix "Invalid token" problem? thank you!

**Comment by cloudwebrtc** [comment]
This is a problem with the .gn file format. You need to check whether it contains spaces, tabs and other invalid characters.
