### ISSUE TITLE
Compile fail for m125

### ISSUE THREAD

**Issue by yuemenglong** [webrtc-sdk/libwebrtc#101]
I use ubuntu:20.04, this is my compile steps:

solutions = [
  {
    "name"        : 'src',
    "url"         : 'https://github.com/webrtc-sdk/webrtc.git@m125_release',
    "deps_file"   : 'DEPS',
    "managed"     : False,
    "custom_deps" : {
    },
    "custom_vars": {},
  },
]
target_os  = ['linux']

gclient sync

cd /app/webrtc/src
git clone https://github.com/webrtc-sdk/libwebrtc

deps = [ ":webrtc" ] => deps = [ ":webrtc" , "//libwebrtc" ]

export ARCH=x64

gn gen out/x64_release --args="target_os=\"linux\" target_cpu=\"$ARCH\" is_debug=false rtc_include_tests=false rtc_use_h264=true ffmpeg_branding=\"Chrome\" is_component_build=false use_rtti=true use_custom_libcxx=false rtc_enable_protobuf=false"

ninja -C out/x64_release libwebrtc

And it occurs:

In file included from ../../libwebrtc/src/rtc_peerconnection_impl.cc:12:
../../libwebrtc/src/rtc_media_stream_impl.h:38:36: error: no type named 'RTCStatsMemberInterface' in namespace 'webrtc'
   38 |   RTCStatsMemberImpl(const webrtc::RTCStatsMemberInterface* member)
      |                            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:151:17: error: no type named 'RTCStatsMemberInterface' in namespace 'webrtc'
  151 |   const webrtc::RTCStatsMemberInterface* member_;
      |         ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:46:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   46 |       case webrtc::RTCStatsMemberInterface::kBool:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:48:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   48 |       case webrtc::RTCStatsMemberInterface::kInt32:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:50:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   50 |       case webrtc::RTCStatsMemberInterface::kUint32:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:52:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   52 |       case webrtc::RTCStatsMemberInterface::kInt64:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:54:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   54 |       case webrtc::RTCStatsMemberInterface::kUint64:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:56:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   56 |       case webrtc::RTCStatsMemberInterface::kDouble:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:58:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   58 |       case webrtc::RTCStatsMemberInterface::kString:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:60:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   60 |       case webrtc::RTCStatsMemberInterface::kSequenceBool:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:62:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   62 |       case webrtc::RTCStatsMemberInterface::kSequenceInt32:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:64:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   64 |       case webrtc::RTCStatsMemberInterface::kSequenceUint32:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:66:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   66 |       case webrtc::RTCStatsMemberInterface::kSequenceInt64:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:68:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   68 |       case webrtc::RTCStatsMemberInterface::kSequenceUint64:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:70:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   70 |       case webrtc::RTCStatsMemberInterface::kSequenceDouble:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:72:20: error: no member named 'RTCStatsMemberInterface' in namespace 'webrtc'
   72 |       case webrtc::RTCStatsMemberInterface::kSequenceString:
      |            ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:82:38: error: no member named 'RTCStatsMember' in namespace 'webrtc'
   82 |     return *member_->cast_to<webrtc::RTCStatsMember<bool>>();
      |                              ~~~~~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:82:57: error: expected '(' for function-style cast or type construction
   82 |     return *member_->cast_to<webrtc::RTCStatsMember<bool>>();
      |                                                     ~~~~^
../../libwebrtc/src/rtc_media_stream_impl.h:82:60: error: expected expression
   82 |     return *member_->cast_to<webrtc::RTCStatsMember<bool>>();
      |                                                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Is there anything wrong?
Thank you very much!!

**Comment by cloudwebrtc** [comment]
sorry, I forget to merge this PR https://github.com/webrtc-sdk/libwebrtc/pull/97.
