### ISSUE TITLE
[windows] Crash accessing video camera if the camera is used by other app

### ISSUE THREAD

**Issue by ashellunts** [webrtc-sdk/libwebrtc#18]
Crash occurs when calling `base_->factory_->CreateVideoTrack(source, uuid.c_str());` in `FlutterMediaStream::GetUserVideo`.

Crash is inside libwebrtc.
Also there is no (or I don't see) a way to understand that camera is busy and don't call `createVideoTrack`.

**Comment by cloudwebrtc** [comment]
I think this needs to be traced to the video capture device level to find a solution.

https://github.com/webrtc-sdk/webrtc/tree/main/modules/video_capture/windows

**Comment by cloudwebrtc** [comment]
1, If flutter-webrtc itself needs to create video capture multiple times, we need a video capture proxy to allow multiple sinks to capture the capture stream

2,If other applications occupy the camera, we can only inform the user that the camera cannot be obtained and prevent the crash from occurring.

**Comment by ashellunts** [comment]
Sounds good 👍

**Comment by ashellunts** [comment]
Currently https://github.com/webrtc-sdk/webrtc/blob/main/test/vcm_capturer.h is used for capturing on windows.
Will try to fix the bug if it takes not too long.
