### ISSUE TITLE
Seems like code is either broken or need some information for compilation error. Can't find class "webrtc::AudioDeviceSink" anywhere.

### ISSUE THREAD

**Issue by shalabhawasthi** [webrtc-sdk/libwebrtc#42]
Hi,

Some recent changes were made in the file "src\rtc_audio_device_impl.h" due to which I cannot compile the latest code.

"class AudioDeviceImpl : public RTCAudioDevice, public **webrtc::AudioDeviceSink**"

I cannot find any header file with the class "AudioDeviceSink" declaration. Can you please point me in the correct direction?
I also searched in webrtc source from the m104 branch.

Thanks in advance.

**Comment by cloudwebrtc** [comment]
hi, Here is the interface definition file.
https://github.com/webrtc-sdk/webrtc/blob/m104_release/modules/audio_device/include/audio_device.h#L24

**Comment by shalabhawasthi** [comment]
> hi, Here is the interface definition file. https://github.com/webrtc-sdk/webrtc/blob/m104_release/modules/audio_device/include/audio_device.h#L24

Thank you very much. Really appreciate your quick response and hard work of the team on the project.
