### ISSUE TITLE
使用jpeg库时，boolean会重复定义

### ISSUE THREAD

**Issue by zjzhang-cn** [webrtc-sdk/libwebrtc#49]
rpcndr.h定义的boolean 会与 jmorecfg.h定义的boolean冲突
![image](https://user-images.githubusercontent.com/1081308/196953650-112ac60b-c335-4b17-b4bb-ec8a834f09f2.png)
![image](https://user-images.githubusercontent.com/1081308/196953828-97b0318f-bac8-4ccc-9c2e-f08e349520d2.png)
![image](https://user-images.githubusercontent.com/1081308/196953865-4265f079-5b3d-4c4e-a7c1-934d407ecf1e.png)

**Comment by nikohpng** [comment]
相同的问题，有解决方法吗

**Comment by nikohpng** [comment]
解决了，安装官网win编译[jconfig.h.in](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1f55ae7b0fa3acc348a630171617d0e56d922b68/win/jconfig.h.in)所说：
```
/* Define "boolean" as unsigned char, not int, per Windows custom */
#ifndef __RPCNDR_H__            /* don't conflict if rpcndr.h already read */
typedef unsigned char boolean;
#endif
#define HAVE_BOOLEAN            /* prevent jmorecfg.h from redefining it */
```
在build.gn 或者 引入上面加入 `HAVE_BOOLEAN` 即可

**Comment by cloudwebrtc** [comment]
冲突已修复 https://github.com/webrtc-sdk/libwebrtc/commit/0372921774314aee674758f39f2dfae8329830d1
