### ISSUE TITLE
question: hard compile

### ISSUE THREAD

**Issue by fawdlstty** [webrtc-sdk/libwebrtc#5]
The dependencies required for compilation cannot be accessed directly in China, which brings great obstacles to compilation. Can all the dependencies be placed in the repo, and the compilation project only needs Cmake?

**Comment by cloudwebrtc** [comment]
I think this is difficult because the code tree of google webrtc completely relies on the GN compilation system, but I will use GitHub actions to provide pre-compiled binary SDK here, so you don't need to compile it yourself in the future.
