### ISSUE TITLE
JPEG parameter struct mismatch

### ISSUE THREAD

**Issue by nikohpng** [webrtc-sdk/libwebrtc#61]
## Description

I build myself libwebrtc in window11. But in jpeg, It can't run!
like this:
```
JPEG parameter struct mismatch: library thinks size is 520, caller expects 504
```
How can i fix it?

**Comment by cloudwebrtc** [comment]
Please try this fix https://github.com/webrtc-sdk/libwebrtc/commit/0372921774314aee674758f39f2dfae8329830d1

**Comment by nikohpng** [comment]
Ok, Thanks. I will test it

**Comment by nikohpng** [comment]
I have test it. In my env, I don't need `HAVE_BOOLEAN` in DEP.
