### ISSUE TITLE
Conan support

### ISSUE THREAD

**Issue by k-wasniowski** [webrtc-sdk/libwebrtc#82]
Did you consider adding conan support?

**Comment by k-wasniowski** [comment]
If you could add me as a contributor, I would like to work on providing conan support if maintainers are interested.

**Comment by cloudwebrtc** [comment]
hey @k-wasniowski, I haven't used Conan before, but it sounds great, and have added you to maintainers.

**Comment by k-wasniowski** [comment]
Awesome! @cloudwebrtc I will be working on it on this branch: https://github.com/webrtc-sdk/libwebrtc/tree/feat/conan-support. In the long term what about adding it to the global Conan center? https://conan.io/center/
